### ISSUE TITLE
agregando imagenes

### ISSUE THREAD

**Issue by HuamanGalindo** [HuamanGalindo/tours-peru#4]
avance

**Comment by cibertp** [comment]
1.  @HuamanGalindo   tienes que integrar al proyecto los fragmet necesarios , si es posible implementarlo solo con Liner layout eso depende ti.. dentro de ellos vas poner las imagines dentro de un scroll view ... 
2. necesitas descargar algunas fuentes de Internet trabaja con tres imágenes de diferente departamentos que sean de cusco amazonas y ayacucho luego incorporemos mas
3. crea un antivity cusco para enlazar el click del layout de la imagen  del departamento

**Comment by HuamanGalindo** [comment]
ya lo implemente los que usted me dijo ... todo esta bien sigamos con la siguiente actividad

**Comment by cibertp** [comment]
perfeto entonces damos como caso cerrado esto
